./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-18-HMS_Acacia.htm"                    --imma=../../imma/Acacia.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Achilles.htm"                  --imma=../../imma/Achilles.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-01-HMS_Africa.htm"                    --imma=../../imma/Africa.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-21-HMS_Alacrity.htm"                  --imma=../../imma/Alacrity.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-01-HMS_Albemarle.htm"                 --imma=../../imma/Albemarle.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-01-HMS_Albion.htm"                    --imma=../../imma/Albion.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Alcantara.htm"                 --imma=../../imma/Alcantara.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-50-HMS_Alert.htm"                     --imma=../../imma/<i>Alert</i>.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-18-HMS_Algerine.htm"                  --imma=../../imma/Algerine.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Almanzora.htm"                 --imma=../../imma/Almanzora.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Alsatian.htm"                  --imma=../../imma/Alsatian.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-10-HMS_Amazon.htm"                    --imma=../../imma/Amazon.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Ambrose.htm"                   --imma=../../imma/Ambrose.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Amethyst.htm"                  --imma=../../imma/Amethyst.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Amphitrite.htm"                --imma=../../imma/Amphitrite.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Andes.htm"                     --imma=../../imma/Andes.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Antrim.htm"                    --imma=../../imma/Antrim.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-11-HMS_Aphis.htm"                     --imma=../../imma/Aphis.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Argonaut.htm"                  --imma=../../imma/Argonaut.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-04-HMS_Ark_Royal.htm"                 --imma=../../imma/Ark_Royal.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Arlanza.htm"                   --imma=../../imma/Arlanza.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_ArmadaleCastle.htm"            --imma=../../imma/Armadale_Castle.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Artois.htm"                    --imma=../../imma/Artois.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Astraea.htm"                   --imma=../../imma/Astraea.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-33-HMS_Atalanta.htm"                  --imma=../../imma/Atalanta.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-10-HMS_Attack.htm"                    --imma=../../imma/Attack.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Attentive.htm"                 --imma=../../imma/Attentive.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Avenger.htm"                   --imma=../../imma/Avenger.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Avoca.htm"                     --imma=../../imma/Avoca.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Bacchante.htm"                 --imma=../../imma/Bacchante.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-75-RFA_Bacchus.htm"                   --imma=../../imma/Bacchus.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-01-HMS_Barham.htm"                    --imma=../../imma/Barham.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-09-HMS_Bayano.htm"                    --imma=../../imma/Bayano.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-11-HMS_Bee.htm"                       --imma=../../imma/Bee.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-04-HMS_Ben-my-Chree.htm"              --imma=../../imma/Ben-My-Chree.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Berwick.htm"                   --imma=../../imma/<i>Berwick</i>.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Birmingham.htm"                --imma=../../imma/Birmingham.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Blenheim.htm"                  --imma=../../imma/<i>Blenheim</i>.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-18-HMS_Bluebell.htm"                  --imma=../../imma/Bluebell.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-19-HMS_Bramble.htm"                   --imma=../../imma/Bramble.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Bristol.htm"                   --imma=../../imma/Bristol.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-01-HMS_Britannia.htm"                 --imma=../../imma/Britannia.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-19-HMS_Britomart.htm"                 --imma=../../imma/Britomart.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-18-HMS_Cadmus.htm"                    --imma=../../imma/Cadmus.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-01-HMS_Caesar.htm"                    --imma=../../imma/Caesar.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Cairo.htm"                     --imma=../../imma/Cairo.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Calcutta.htm"                  --imma=../../imma/<i>Calcutta</i>.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Calgarian.htm"                 --imma=../../imma/<i>Calgarian</i>.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Calliope.htm"                  --imma=../../imma/Calliope.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Calypso.htm"                   --imma=../../imma/Calypso.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Cambrian.htm"                  --imma=../../imma/Cambrian.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-01-HMS_Canopus.htm"                   --imma=../../imma/Canopus.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Canterbury.htm"                --imma=../../imma/<i>Canterbury</i>.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Capetown.htm"                  --imma=../../imma/Capetown.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Caradoc.htm"                   --imma=../../imma/Caradoc.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Cardiff.htm"                   --imma=../../imma/Cardiff.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Carlisle.htm"                  --imma=../../imma/<i>Carlisle</i>.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Carmania.htm"                  --imma=../../imma/Carmania.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Carnarvon.htm"                 --imma=../../imma/Carnarvon.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Caroline.htm"                  --imma=../../imma/<i>Caroline</i>.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Caronia.htm"                   --imma=../../imma/<i>Caronia</i>.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-09-HMS_Carrigan_Head.htm"             --imma=../../imma/Carrigan_Head.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Castor.htm"                    --imma=../../imma/Castor.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Cedric.htm"                    --imma=../../imma/Cedric.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Celtic.htm"                    --imma=../../imma/Celtic.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Centaur.htm"                   --imma=../../imma/<i>Centaur</i>.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Ceres.htm"                     --imma=../../imma/<i>Ceres</i>.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Challenger.htm"                --imma=../../imma/Challenger.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Changuinola.htm"               --imma=../../imma/Changuinola.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Chatham.htm"                   --imma=../../imma/Chatham.imma                     # Part 1 of 2)
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-10-HMS_Christopher.htm"               --imma=../../imma/<i>Christopher</i>.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-11-HMS_Cicala.htm"                    --imma=../../imma/Cicala.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-08-HMS_City_of_London.htm"            --imma=../../imma/<i>City_of_London</i>.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-18-HMS_Clio.htm"                      --imma=../../imma/Clio.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Cochrane.htm"                  --imma=../../imma/Cochrane.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-11-HMS_Cockchafer.htm"                --imma=../../imma/Cockchafer.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-10-HMS_Colne.htm"                     --imma=../../imma/Colne.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Colombo.htm"                   --imma=../../imma/Colombo.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Columbella.htm"                --imma=../../imma/<i>Columbella</i>.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-01-HMS_Commonwealth.htm"              --imma=../../imma/Commonwealth.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Comus.htm"                     --imma=../../Comus.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Constance.htm"                 --imma=../../Constance.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-18-HMS_Cornflower.htm"                --imma=../../Cornflower.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Cornwall.htm"                  --imma=../../imma/Cornwall.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-09-HMS_Coronado.htm"                  --imma=../../imma/Coronado.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Coventry.htm"                  --imma=../../imma/Coventry.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Crescent.htm"                  --imma=../../imma/Crescent.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-11-HMS_Cricket.htm"                   --imma=../../imma/Cricket.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-18-HMS_Crocus.htm"                    --imma=../../Crocus.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Cumberland.htm"                --imma=../../imma/<i>Cumberland</i>.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Curlew.htm"                    --imma=../../imma/Curlew.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-18-HMS_Cyclamen.htm"                  --imma=../../Cyclamen.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-75-RIMS_Dalhousie.htm"                --imma=../../imma/Dalhousie.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Danae.htm"                     --imma=../../Danae.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Dartmouth.htm"                 --imma=../../imma/Dartmouth.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Dauntless.htm"                 --imma=../../imma/Dauntless.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Defence.htm"                   --imma=../../imma/Defence.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Delhi.htm"                     --imma=../../Delhi.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Despatch.htm"                  --imma=../../Despatch.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Devonshire.htm"                --imma=../../imma/Devonshire.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Diana.htm"                     --imma=../../imma/<i>Diana</i>.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Digby.htm"                     --imma=../../imma/Digby.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Diomede.htm"                   --imma=../../Diomede.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Donegal.htm"                   --imma=../../imma/Donegal.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Dragon.htm"                    --imma=../../imma/Dragon.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Drake.htm"                     --imma=../../imma/<i>Drake</i>.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-22-HMS_Dryad.htm"                     --imma=../../imma/Dryad.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Dublin.htm"                    --imma=../../Dublin.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Duke_of_Edinburgh.htm"         --imma=../../imma/Duke_of_Edinburgh.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Dunedin.htm"                   --imma=../../imma/<i>Dunedin</i>.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Durban.htm"                    --imma=../../imma/Durban.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-19-HMS_Dwarf.htm"                     --imma=../../imma/Dwarf.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Ebro.htm"                      --imma=../../imma/Ebro.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Eclipse.htm"                   --imma=../../imma/Eclipse.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Edinburgh_Castle.htm"          --imma=../../imma/<i>Edinburgh_Castle</i>.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-04-HMS_Empress.htm"                   --imma=../../imma/Empress.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_EmpressOfBritain.htm"          --imma=../../imma/Empress_of_Britain.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Empress_of_Japan.htm"          --imma=../../imma/Empress_of_Japan.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-18-HMS_Endeavour.htm"                 --imma=../../imma/Endeavour.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Endymion.htm"                  --imma=../../imma/Endymion.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-18-HMS_Enterprise.htm"                --imma=../../imma/Enterprise.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-03-HMS_Erebus.htm"                    --imma=../../imma/<i>Erebus</i>.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Eskimo.htm"                    --imma=../../imma/Eskimo.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-18-HMS_Espiegle.htm"                  --imma=../../imma/Espiegle.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Essex.htm"                     --imma=../../imma/<i>Essex</i>.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Europa.htm"                    --imma=../../imma/<i>Europa</i>.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Euryalus.htm"                  --imma=../../imma/Euryalus.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-01-HMS_Exmouth.htm"                   --imma=../../imma/Exmouth.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Falmouth.htm"                  --imma=../../imma/Falmouth.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-10-HMS_Fame.htm"                      --imma=../../imma/Fame.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-18-HMS_Fantome.htm"                   --imma=../../imma/Fantome.imma                    # Part 1 of 2
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Fearless.htm"                  --imma=../../imma/Fearless.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-75-RFA_Fortol.htm"                    --imma=../../imma/Fortol.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Fox.htm"                       --imma=../../imma/Fox.imma                        # Part 1 of 2
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-18-HMS_Foxglove.htm"                  --imma=../../imma/Foxglove.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-31-HMS_Foyle.htm"                     --imma=../../imma/Foyle.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Galatea.htm"                   --imma=../../imma/<i>Galatea</i>.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Gibraltar.htm"                 --imma=../../imma/Gibraltar.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Glasgow.htm"                   --imma=../../imma/Glasgow.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-01-HMS_Glory.htm"                     --imma=../../imma/Glory.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Gloucester.htm"                --imma=../../imma/Gloucester.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Gloucestershire.htm"           --imma=../../imma/Gloucestershire.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-11-HMS_Glowworm.htm"                  --imma=../../imma/Glowworm.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-11-HMS_Gnat.htm"                      --imma=../../imma/Gnat.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-01-HMS_Goliath.htm"                   --imma=../../imma/Goliath.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Grafton.htm"                   --imma=../../imma/<i>Grafton</i>.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Hampshire.htm"                 --imma=../../imma/Hampshire.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-01-HMS_Hannibal.htm"                  --imma=../../imma/<i>Hannibal</i>.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Hawkins.htm"                   --imma=../../imma/Hawkins.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Hermione.htm"                  --imma=../../imma/Hermione.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-01-HMS_Hibernia.htm"                  --imma=../../imma/Hibernia.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Highflyer.htm"                 --imma=../../imma/Highflyer.imma                   # Part 3 of 3
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Hilary.htm"                    --imma=../../imma/Hilary.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Hildebrand.htm"                --imma=../../imma/Hildebrand.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Himalaya.htm"                  --imma=../../imma/Himalaya.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-18-HMS_Hollyhock.htm"                 --imma=../../imma/Hollyhock.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-02-HMS_Hood.htm"                      --imma=../../imma/Hood.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-03-HMS_Humber.htm"                    --imma=../../imma/Humber.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Hyacinth.htm"                  --imma=../../imma/Hyacinth.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-01-HMS_Implacable.htm"                --imma=../../imma/Implacable.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Inconstant.htm"                --imma=../../imma/Inconstant.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_India.htm"                     --imma=../../imma/India.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-02-HMS_Inflexible.htm"                --imma=../../imma/Inflexible.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Intrepid.htm"                  --imma=../../imma/<i>Intrepid</i>.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-02-HMS_Invincible.htm"                --imma=../../imma/Invincible.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Iphigenia.htm"                 --imma=../../imma/<i>Iphigenia</i>.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-18-HMS_Iroquois.htm"                  --imma=../../imma/Iroquois.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Isis.htm"                      --imma=../../imma/<i>Isis</i>.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-10-HMS_Jed.htm"                       --imma=../../imma/<i>Jed</i>.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-18-HMS_Jessamine.htm"                 --imma=../../imma/<i>Jessamine</i>.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Juno.htm"                      --imma=../../imma/Juno.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-01-HMS_Jupiter.htm"                   --imma=../../imma/Jupiter.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-10-HMS_Kennet.htm"                    --imma=../../imma/Kennet.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Kent.htm"                      --imma=../../imma/Kent.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Kildonan_Castle.htm"           --imma=../../imma/Kildonan_Castle.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Kinfauns_Castle.htm"           --imma=../../imma/Kinfauns_Castle.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_King_Alfred.htm"               --imma=../../imma/King_Alfred.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-11-HMS_Kinsha.htm"                    --imma=../../imma/Kinsha.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-09-HMS_Knight_Templar.htm"            --imma=../../imma/Knight_Templar</b></a>
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-18-HMS_Laburnum.htm                   --imma=../../imma/"Laburnum.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Laconia.htm"                   --imma=../../imma/Laconia.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-09-HMS_Lama.htm"                      --imma=../../imma/Lama.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Lancaster.htm"                 --imma=../../imma/Lancaster.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Laurentic.htm"                 --imma=../../imma/Laurentic.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-09-HMS_Lepanto.htm"                   --imma=../../imma/Lepanto.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Leviathan.htm"                 --imma=../../imma/<i>Leviathan</i>.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Liverpool.htm"                 --imma=../../imma/Liverpool.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-31-HMS_Lord_Minto.htm"                --imma=../../imma/Lord_Minto.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Lowestoft.htm"                 --imma=../../imma/Lowestoft.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-09-HMS_Lunka.htm"                     --imma=../../imma/Lunka.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-03-HMS_M.23.htm"                      --imma=../../imma/M.23.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-03-HMS_M.24.htm"                      --imma=../../imma/M.24.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-03-HMS_M.25.htm"                      --imma=../../imma/M.25.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-03-HMS_M.29.htm"                      --imma=../../imma/M.29.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-03-HMS_M.31.htm"                      --imma=../../imma/M.31.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-03-HMS_M.33.htm"                      --imma=../../imma/M.33.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Macedonia.htm"                 --imma=../../imma/Macedonia.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-18-HMS_Magnolia.htm"                  --imma=../../imma/Magnolia.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-01-HMS_Malaya.htm"                    --imma=../../imma/Malaya.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-04-HMS_Manica.htm"                    --imma=../../imma/Manica.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-11-HMS_Mantis.htm"                    --imma=../../imma/Mantis.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Mantua.htm"                    --imma=../../imma/Mantua.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-22-HMS_Marazion.htm"                  --imma=../../imma/Marazion.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Marmora.htm"                   --imma=../../imma/<i>Marmora</i>.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-18-HMS_Merlin.htm"                    --imma=../../imma/Merlin_1.imma          ####  Split initial file
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-31-HMS_Merlin.htm"                    --imma=../../imma/Merlin_2.imma          ####  Split initial file
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-03-HMS_Mersey.htm"                    --imma=../../imma/Mersey.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Minerva.htm"                   --imma=../../imma/Minerva.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Minotaur.htm"                  --imma=../../imma/Minotaur.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Moldavia.htm"                  --imma=../../imma/Moldavia.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-11-HMS_Moorhen.htm"                   --imma=../../imma/Moorhen.imma           # Part 1 of 3
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Morea.htm"                     --imma=../../imma/Morea.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Motagua.htm"                   --imma=../../imma/Motagua.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-11-HMS_Moth.htm"                      --imma=../../imma/Moth.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-18-HMS_Mutine.htm"                    --imma=../../imma/Mutine.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-04-HMS_Nairana.htm"                   --imma=../../imma/Nairana.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-09-HMS_Naneric.htm"                   --imma=../../imma/Naneric.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-02-HMS_New_Zealand.htm"               --imma=../../imma/New_Zealand.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Newcastle.htm"                 --imma=../../imma/Newcastle.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-75-RIMS_Northbrook.htm"               --imma=../../imma/Northbrook.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-18-HMS_Odin.htm"                      --imma=../../imma/Odin.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Ophir.htm"                     --imma=../../imma/Ophir.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Orama.htm"                     --imma=../../imma/Orama.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Orbita.htm"                    --imma=../../imma/Orbita.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Orcoma.htm"                    --imma=../../imma/Orcoma.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Orotava.htm"                   --imma=../../imma/Orotava.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Orvieto.htm"                   --imma=../../imma/Orvieto.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Otranto.htm"                   --imma=../../imma/Otranto.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-10-HMS_Otter.htm"                     --imma=../../imma/Otter.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Otway.htm"                     --imma=../../imma/Otway.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-31-HMS_Parramatta.htm"                --imma=../../imma/Parramatta.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Patia.htm"                     --imma=../../imma/Patia.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Patuca.htm"                    --imma=../../imma/Patuca.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-04-HMS_Pegasus.htm"                   --imma=../../imma/Pegasus.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Pelorus.htm"                   --imma=../../imma/Pelorus.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-31-HMS_Persian_Empire.htm"            --imma=../../imma/Persian_Empire.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-09-HMS_Perth.htm"                     --imma=../../imma/<i>Perth</i>.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-22-HMS_Petersfield.htm"               --imma=../../imma/<i>Petersfield</i>.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Phaeton.htm"                   --imma=../../imma/Phaeton.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Philomel.htm"                  --imma=../../imma/Philomel.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Princess.htm"                  --imma=../../imma/Princess.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-02-HMS_Princess_Royal.htm"            --imma=../../imma/Princess_Royal.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Proserpine.htm"                --imma=../../imma/Proserpine.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Psyche.htm"                    --imma=../../imma/Psyche.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Pyramus.htm"                   --imma=../../imma/Pyramus.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Raleigh.htm"                   --imma=../../imma/Raleigh.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-75-RFA_Rapidol.htm"                   --imma=../../imma/Rapidol.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-04-HMS_Raven_II.htm"                  --imma=../../imma/<i>Raven_II</i>.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-02-HMS_Renown.htm"                    --imma=../../imma/Renown.imma             # Part 1 of 2
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-02-HMS_Repulse.htm"                   --imma=../../imma/Repulse.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-10-HMS_Ribble.htm"                    --imma=../../imma/Ribble.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-18-HMS_Rinaldo.htm"                   --imma=../../imma/Rinaldo.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-18-HMS_Rosario.htm"                   --imma=../../imma/<i>Rosario</i>.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Roxburgh.htm"                  --imma=../../imma/Roxburgh.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-05-HMS_St_George.htm"                 --imma=../../imma/<i>St_George</i>.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-11-HMS_Sandpiper.htm"                 --imma=../../imma/<i>Sandpiper</i>.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-31-HMS_Sapper.htm"                    --imma=../../imma/Sapper.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Sapphire.htm"                  --imma=../../imma/Sapphire.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-31-HMS_Saxon.htm"                     --imma=../../imma/Saxon.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-11-HMS_Scarab.htm"                    --imma=../../imma/Scarab.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-18-HMS_Sealark.htm"                   --imma=../../imma/Sealark.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-03-HMS_Severn.htm"                    --imma=../../imma/Severn.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-18-HMS_Shearwater.htm"                --imma=../../imma/Shearwater.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Sirius.htm"                    --imma=../../imma/<i>Sirius</i>.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-11-HMS_Snipe.htm"                     --imma=../../imma/Snipe.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Southampton.htm"               --imma=../../imma/Southampton.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Suffolk.htm"                   --imma=../../imma/Suffolk.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Sutlej.htm"                    --imma=../../imma/Sutlej.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-09-HMS_Suva.htm"                      --imma=../../imma/Suva.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-01-HMS_Swiftsure.htm"                 --imma=../../imma/Swiftsure.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-06-HMAS_Sydney.htm"                   --imma=../../imma/Sydney.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Talbot.htm"                    --imma=../../imma/Talbot.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-80-HMS_Tamar.htm"                     --imma=../../imma/Tamar.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-11-HMS_Tarantula.htm"                 --imma=../../imma/Tarantula.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-10-HM_TB_037.htm"                     --imma=../../imma/TB.037.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-10-HM_TB_35.htm"                      --imma=../../imma/TB.35.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-10-HM_TB_36.htm"                      --imma=../../imma/TB.36.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-11-HMS_Teal.htm"                      --imma=../../imma/Teal.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-01-HMS_Temeraire.htm"                 --imma=../../imma/Temeraire.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-31-HMS_Tenby_Castle.htm"              --imma=../../imma/Tenby_Castle.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Teutonic.htm"                  --imma=../../imma/Teutonic.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Theseus.htm"                   --imma=../../imma/<i>Theseus</i>.imma
###./scrape_positions.perl  --url="http://www.naval-history.net/OWShips-WW1-19-HMS_Thistle.htm"                   --imma=../../imma/Thistle_1.imma        ## Split original
###./scrape_positions.perl  --url="http://www.naval-history.net/OWShips-WW1-33-HMS_Thistle.htm"                   --imma=../../imma/Thistle_2.imma        ## Split original
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-50-HMS_Titania.htm"                   --imma=../../imma/Titania.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Topaze.htm"                    --imma=../../imma/Topaze.imma
###./scrape_positions.perl  --url="http://www.naval-history.net/OWShips-WW1-18-HMS_Torch.htm"                     --imma=../../imma/Torch_1.imma          ## Split original  
###./scrape_positions.perl  --url="http://www.naval-history.net/OWShips-WW1-10-HMS_Torch.htm"                     --imma=../../imma/Torch_2.imma          ## Split original
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-09-HMS_Trent.htm"                     --imma=../../imma/Trent.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-18-HMAS_Una.htm"                      --imma=../../imma/Una.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-10-HMS_Usk.htm"                       --imma=../../imma/Usk.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-18-HMS_Valerian.htm"                  --imma=../../imma/Valerian.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-01-HMS_Valiant.htm"                   --imma=../../imma/Valiant.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-01-HMS_Vengeance.htm"                 --imma=../../imma/Vengeance.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Venus.htm"                     --imma=../../imma/Venus.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-18-HMS_Veronica.htm"                  --imma=../../imma/Veronica.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Victorian.htm"                 --imma=../../imma/<i>Victorian</i>.imma
###./scrape_positions.perl  --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Vindictive.htm"                --imma=../../imma/Vindictive_1.imma          ## Split original
###./scrape_positions.perl  --url="http://www.naval-history.net/OWShips-WW1-04-HMS_Vindictive.htm"                --imma=../../imma/Vindictive_2.imma          ## Split original
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-10-HMS_Virago.htm"                    --imma=../../imma/Virago.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-08-HMS_Virginian.htm"                 --imma=../../imma/Virginian.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-10-HMAS_Warrego.htm"                  --imma=../../imma/Warrego.imma
###./scrape_positions.perl  --url="http://www.naval-history.net/OWShips-WW1-05-HMS_Warrior.htm"                   --imma=../../imma/Warrior_1.imma          ## Split original
###./scrape_positions.perl  --url="http://www.naval-history.net/OWShips-WW1-33-HMS_Warrior.htm"                   --imma=../../imma/Warrior_2.imma          ## Split original
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-01-HMS_Warspite.htm"                  --imma=../../imma/Warspite.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-10-HMS_Welland.htm"                   --imma=../../imma/<i>Welland</i>.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Weymouth.htm"                  --imma=../../imma/Weymouth.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-10-HMS_Whiting.htm"                   --imma=../../imma/Whiting.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-11-HMS_Widgeon.htm"                   --imma=../../imma/Widgeon.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-18-HMS_Wistaria.htm"                  --imma=../../imma/Wistaria.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-40-HMS_Wonganella.htm"                --imma=../../imma/Wonganella.imma
./scrape_positions.perl     --url="http://www.naval-history.net/OWShips-WW1-11-HMS_Woodcock.htm"                  --imma=../../imma/Woodcock.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-11-HMS_Woodlark.htm"                  --imma=../../imma/<i>Woodlark</i>.imma
#./scrape_positions.perl    --url="http://www.naval-history.net/OWShips-WW1-06-HMS_Yarmouth.htm"                  --imma=../../imma/<i>Yarmouth</i>.imma
